### PR TITLE
Task/tec 77/migrating scss to tailwindcss

### PR DESCRIPTION
**Pull request by Benrobo**
Revamp the frontend codebase using `tailwindcss` in place of `Scss`.

This PR consists of the following pages / components

- Onboarding
- Login and Signup pages
- Input component
- VerifyAccount page

### CODE REVIEW

**Comment by walter708** [comment]
Hi @Benrobo I noticed that the checkbox on search for business is looking outdated please could you use the one that looks like this 
image

**Comment by walter708** [comment]
I also noticed that the cards are looking narrow 
image

**Comment by walter708** [comment]
I also noticed that if am on the explore page, when I reload the page it takes me back to the search page 
https://github.com/Luminescence-inc/Project-Delta-Frontend/assets/55052227/8d11d5f0-d850-4ec3-8f25-d13d45e7002f

**Comment by walter708** [comment]
So I still see the signup button on the home page even when I am logged in an when I click on it, it takes me to update user profile

https://github.com/Luminescence-inc/Project-Delta-Frontend/assets/55052227/8e6efc86-cd54-4bf0-8cb7-90d911caa62a

**Comment by walter708** [comment]
I know it's front end and it's easy to miss things. I would to ask if you can make the point on this list a cursor
image

**Comment by Benrobo** [comment]
> I also noticed that the cards are looking narrow image
> 
> image
> 
> image

@osxar I'm working on this fix on a separate ticket and a separate pr would be made for this.

**Comment by walter708** [comment]
Hi @Benrobo  thanks for the changes made, there is are still some changes left. please do comment when they have been made

**Comment by Benrobo** [comment]
> So I still see the signup button on the home page even when I am logged in an when I click on it, it takes me to update user profile
> 
>  id.2.mp4

@walter708  Yeah, this has been resolved in other PR, you would get the main update once they are merged

**Pull request merged**
